### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adviksinghania**
Add ArnoldC tutorial

### CODE REVIEW

**Comment by adityaoberai** [comment]
@adviksinghania I really appreciate you adding your own tutorial here. Could you also add a sample of the "Hello, World" ArnoldC code in the description? The process of installing and running the file is great but I would love to know what that code looks like too.

**Comment by adviksinghania** [comment]
Sure Sir. Should I add the code in the description of this PR or in the README.md ?

**Comment by adityaoberai** [comment]
> Sure Sir. Should I add the code in the description of this PR or in the README.md ?

I have a better idea
Why don't you write a little article on Dev.to about ArnoldC and share that after it is done?
It is one of the challenges this week after all too :)

**Comment by adviksinghania** [comment]
Okay sir, but I've already added the Devpost submission link in the README which has a little overview and the instructions on how to install and use it.

**Comment by adityaoberai** [comment]
It has the instructions to install but not how to write the code, which is an essential part of the tutorial

**Comment by adityaoberai** [comment]
Do let me know whenever you do create that. If you do, make sure to talk about the language, its benefits, installation (that you already have), and writing the code as well.

**Pull request closed without merging**
